 # 忽视的文件夹
 resource-ignore-patterns:
  - node_modules
  - test
  - lib
  - .vscode
  - .idea
  - typings
  - README.MD
  - gulpfile.js
  - build
  - example
  - dev

#
# only valid in the outputDirectory.
# javascript-source-patterns:
#  - 'src/**/*.js'
#  - 'index.js'

#
# only valid in the outputDirectory.
 garbage-patterns:
  - tsconfig.json