# resource-ignore-patterns:
#  - dist
#  - out

#
# only valid in the outputDirectory.
# javascript-source-patterns:
#  - 'src/**/*.js'
#  - 'index.js'

#
# only valid in the outputDirectory.
 garbage-patterns:
  - tsconfig.json